name: KarisomeBlocks
main: amata1219.karisome.block.KarisomeBlock
version: 1.0.0
api-version: 1.18
author: '@amata1219'

commands:
  karisome:
    permission: karisome.block.main
    permission-message: 'You do not have the permission.'